name: "Khirale Izpower MQTT Gateway"
version: "0.2.14"
slug: "khirale_izypwoer_mqtt_gateway"
description: "Permet la communication MQTT des équipements Izypower"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  site_code: ""
  allowed_serials: []
  vps_host: "mqtt.khirale.fr"
  vps_port: 8883
  vps_username: ""
  vps_password: ""
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  site_code: str
  allowed_serials:
    - str
  vps_host: str
  vps_port: port
  vps_username: str
  vps_password: password
